# Generated by Django 5.0.4 on 2024-04-16 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_customer_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='leave_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 16, 11, 38, 42, 796970, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
