# Generated by Django 5.0.4 on 2024-04-16 09:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_customer_leave_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='hourly_price',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.price'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='leave_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 16, 11, 43, 33, 913159, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='seat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pages.seat'),
        ),
    ]
