# Generated by Django 5.0.4 on 2024-04-18 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_customer_hourly_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='seat',
        ),
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='leave_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 18, 6, 1, 0, 8531, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
