# Generated by Django 5.0.4 on 2024-04-18 04:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_customer_seat_seat_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='seat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pages.seat'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='leave_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 18, 6, 1, 32, 729859, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
